Aarhus Web Devloper Corporation/ViewModels/ContactForm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Aarhus_Web_Devloper_Corporation.ViewModels
{
    public class ContactForm
    {
        [Required(ErrorMessage = "Please enter your name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please enter your Email")]
        [Display(Name = "Email")]
        [RegularExpression(@"^([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)$", ErrorMessage ="Enter correct email")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please enter Subject")]
        public string Subject { get; set; }
        [Required(ErrorMessage = "Please enter Message")]
        public string Message { get; set; }
    }
}

Aarhus Web Devloper Corporation/Controllers/ContactFormSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using Umbraco.Core.Models;
using Aarhus_Web_Devloper_Corporation.ViewModels;
using System.Net.Mail;

namespace Aarhus_Web_Devloper_Corporation.Controllers
{
    public class ContactFormSurfaceController : SurfaceController
    {
        // GET: ContactFormSurface
        public ActionResult Index()
        {
            return PartialView("ContactForm", new ContactForm());
        }

        [HttpPost]
        public ActionResult HandleFormSubmit(ContactForm model)
        {
            if (ModelState.IsValid)
            {
                IContent comment = Services.ContentService.CreateContent(model.Subject, CurrentPage.Id, "Message");
                comment.SetValue("messagename", model.Name);
                comment.SetValue("email", model.Email);
                comment.SetValue("subject", model.Subject);
                comment.SetValue("messageContent", model.Message);
                Services.ContentService.Save(comment);
                MailMessage message = new MailMessage();
                message.To.Add("stanislavangelov1995@gmail.com");
                message.Subject = model.Subject;
                message.From = new MailAddress(model.Email, model.Name);
                message.Body = model.Message;
                // <--- no need to send email since already saves as document
                //using (SmtpClient smtp = new SmtpClient())
                //{
                //    smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                //    smtp.UseDefaultCredentials = false;
                //    smtp.EnableSsl = true;
                //    smtp.Host = "smtp.gmail.com";
                //    smtp.Port = 587;
                //    smtp.Credentials = new System.Net.NetworkCredential("stanislavangelov1995@@gmail.com", "");
                //    // send mail
                //    smtp.Send(message);
                //}
                TempData["success"] = true;
                return RedirectToCurrentUmbracoPage();
            }

            else
            {

                return CurrentUmbracoPage();
            }
        }
    }
}

Aarhus Web Devloper Corporation/Views/AboutUs.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.AboutUs>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}
<style>
img{
width:100%;
}
.page-heading{
    height: 5px;
}
</style>
  <!-- Page Header -->
    <header class="masthead" style="background-image: url('img/about-bg.jpg');height: 10vh;">
      <div class="overlay"></div>
      <div class="container" >
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="page-heading"> 
            
            </div>
          </div>
        </div>
      </div>
    </header>
@CurrentPage.GetGridHtml("grid")

Aarhus Web Devloper Corporation/Views/ArticleItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ArticleItem>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

<!-- Page Header -->
    <header class="masthead" style="background-image: url('img/home-bg.jpg')">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
              <div class="page-heading">
              <h1>@Umbraco.Field("articleTitle")</h1>
            </div>
          </div>
        </div>
      </div>
    </header>

@Umbraco.Field("articleContent")

Aarhus Web Devloper Corporation/Views/ArticlesOverview.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ArticlesOverview>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}
@{
	var selection = Model.Content.Site().FirstChild("articlesOverview").Children("articleItem")
						.Where(x => x.IsVisible())
						.OrderBy("UpdateDate desc");
}


<!-- Page Header -->
    <header class="masthead" style="background-image: url('img/home-bg.jpg')">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
              <h1>News Articles</h1>
            </div>
          </div>
        </div>
      </div>
    </header>

<ul>
	@foreach(var item in selection){
		<li>
			<a href="@item.Url">@item.Name</a>
		</li>
	}
</ul>
         

Aarhus Web Devloper Corporation/Views/Comment.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Comment>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}

Aarhus Web Devloper Corporation/Views/ContactUs.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

@* the fun starts here *@
   <!-- Page Header -->
    <header class="masthead" style="background-image: url('img/contact-bg.jpg')">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="page-heading">
              <h1>Contact Me</h1>
              <span class="subheading">Have questions? We have answers.</span>
            </div>
          </div>
        </div>
      </div>
    </header>

<div>
     <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <p>Want to get in touch? Fill out the form below to send us a message.</p>
         
    
    @Html.Action("Index", "ContactFormSurface")
</div>
 </div>
      </div>
    </div>

Aarhus Web Devloper Corporation/Views/HomePage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.HomePage>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

<!-- Page Header -->
    <header class="masthead" style="background-image: url('img/home-bg.jpg')">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
              <div class="page-heading">
              <h1>AWD Corp</h1>
            </div>
          </div>
        </div>
      </div>
    </header>

 @Umbraco.RenderMacro("listNewestProjects")

 @Umbraco.RenderMacro("listNews")

Aarhus Web Devloper Corporation/Views/Login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "Master.cshtml";
}

@* the fun starts here *@

<!-- Page Header -->
    <header class="masthead" style="background-image: url('img/home-bg.jpg')">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
              <div class="page-heading">
              <h1>Login</h1>
            </div>
          </div>
        </div>
      </div>
    </header>
    
    
    @if (!Members.GetCurrentLoginStatus().IsLoggedIn) 
    {
        @Html.Partial("Login")
    }
    else 
    {
        @Html.Partial("Logout")
    }

Aarhus Web Devloper Corporation/Views/MacroPartials/Sitemap.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Umbraco.Core.Models
@using Umbraco.Web


@*
    This snippet makes a list of links of all visible pages of the site, as nested unordered HTML lists.

    How it works:
    - It uses a custom Razor helper called Traverse() to select and display the markup and links.
*@

@{ var selection = Model.Content.Site(); }

<div class="sitemap">
    @* Render the sitemap by passing the root node to the traverse helper, below *@
    @Traverse(selection)
</div>


@* Helper method to traverse through all descendants *@
@helper Traverse(IPublishedContent node)
{
    @* Update the level to reflect how deep you want the sitemap to go *@
    const int maxLevelForSitemap = 4;

    @* Select visible children *@
    var selection = node.Children.Where(x => x.IsVisible() && x.Level <= maxLevelForSitemap).ToArray();

    @* If any items are returned, render a list *@
    if (selection.Length > 0)
    {
        <ul>
            @foreach (var item in selection)
            {
            if(@item.Name != "Sitemap"){
                <li class="level-@item.Level">
                    <a href="@item.Url">@item.Name</a>

                    @* Run the traverse helper again for any child pages *@
                    @Traverse(item)
                </li>
                }
            }
        </ul>
    }
}

Aarhus Web Devloper Corporation/Views/MacroPartials/listNewestProjects.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@{
	var selection = Model.Content.Site().Children().Where(x => x.Name == "Our Projects").First().Children().Where( c => c.GetPropertyValue("projectStatus").ToString() == "42").Take(3);

}

 <a href="/our-projects/"><h1 class="text-center">Projects</h1></a> 
<ul>
    	<div class="container">
      <div class="row">
	@foreach(var item in selection){
	
	
        <div class="col-lg-4 col-md-4 col-mx-4">
         	<a href="@item.Url">@item.GetPropertyValue("projectTitle")</a>
         	<p>@item.GetPropertyValue("projectDescription")</p>
     
        </div>
     

	}
	 </div>
    </div>
</ul>

Aarhus Web Devloper Corporation/Views/MacroPartials/listNews.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@{
	var selection = Model.Content.Site().Children().Where(x => x.Name == "News").First().Children();

}
 <a href="/news"><h1 class="text-center">News</h1></a> 
<ul>
    	<div class="container">
      <div class="row">
	@foreach(var item in selection){
	
	
        <div class="col-lg-4 col-md-4 col-mx-4">
         	<a href="@item.Url">@item.GetPropertyValue("articleTitle")</a>
         	<p>@item.GetPropertyValue("articleContent")</p>
     
        </div>
     

	}
	 </div>
    </div>
</ul>

Aarhus Web Devloper Corporation/Views/MacroPartials/mainMenu.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Umbraco.Web


@*
    This snippet displays a list of links of the pages immediately under the top-most page in the content tree.
    This is the home page for a standard website.
    It also highlights the current active page/section in the navigation with the CSS class "current".
*@

@{ var selection = Model.Content.Site().Children.Where(x => x.IsVisible()).ToArray(); }

@if (selection.Length > 0)
{
    
        foreach (var item in selection)
        {
            <li class="nav-item">
                 <a class="nav-link" href="@item.Url">@item.Name</a>
            </li>
        }
    
}

Aarhus Web Devloper Corporation/Views/MacroPartials/messageMenu.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@{ var selection = CurrentPage.Site().Children().Where("DocumentTypeAlias==\"messageBoard\"").First().Children.Where("Visible");}
    
    @foreach (var item in selection)
        {   <div class="row">
            <div class="container">
            <h1>Name:@item.NameMessage</h1>
            <p> Message: @item.MessageContent</p>
            </div>
</div>        

}

Aarhus Web Devloper Corporation/Views/MacroPartials/navigation.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage


@*
    This snippet displays a list of links of the pages immediately under the top-most page in the content tree.
    This is the home page for a standard website.
    It also highlights the current active page/section in the navigation with the CSS class "current".
*@

@{ var selection = CurrentPage.Site().Children(); }


 <div class="container">
         <a class="navbar-brand" href="/">Home</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="/">Home</a>
            </li>
            @if (selection.Any())
            {
                foreach (var item in selection.Where("UmbracoNaviHide == false"))
                 {
                     <li class="nav-item">
                     <a  class="nav-link" href="@item.Url">@item.Name</a>
                    </li>
                 }
            }
             @Umbraco.RenderMacro("newestMenu")
          </ul>
        </div>
      </div>






 
 
       

Aarhus Web Devloper Corporation/Views/MacroPartials/newestMenu.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@{
	var selection = Model.Content.Site().FirstChild("projectsOverview").Children()
						.Where(x => x.IsVisible() )
						.OrderBy("CreateDate desc");
}


<li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Projects
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/our-projects/">All Projects</a>
          	@foreach(var item in selection){
		if(@item.GetPropertyValue("projectStatus").ToString() == "42"){
			<a class="dropdown-item" href="@item.Url">@item.Name</a>
			
			}
	
	}
       
        </div>
      </li>
      

      

Aarhus Web Devloper Corporation/Views/Master.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Master>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}

<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Aarhus web developer corporation</title>

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="/css/clean-blog.min.css" rel="stylesheet">

  </head>
  
  <body>


	



    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      @Umbraco.RenderMacro("Navigation")
    </nav>
<!-- Body -->
  <div>
    @RenderBody()    
  </div>
  
  
  
  <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted">Copyright &copy; Your Website 2018</p>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>

    <!-- Custom scripts for this template -->
    <script src="js/clean-blog.min.js"></script>
    <script src="~/scripts/jquery.validate.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>
    

  </body>

</html>

Aarhus Web Devloper Corporation/Views/Members.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "Master.cshtml";
}

@* the fun starts here *@

@{
var memberService = ApplicationContext.Current.Services.MemberService;

var activeMembers = memberService.GetMembersByGroup("Active");
var prospectMembers = memberService.GetMembersByGroup("Prospect");
}

<div class="row">
    <div class="col-xs-6">
        <h1 class="text-center">Active members</h1>

        @foreach (var member in activeMembers)
        {
            string fullPath = member.GetValue("photo").ToString();
            string[] substrings = fullPath.Split(',');
            string srcString = substrings[2];
            string[] srcSubStrings = srcString.Split(':');
            string srcPath = srcSubStrings[1].Replace("\"", "");
            srcPath = srcPath.Replace("}", "");

        <div class="col-xs-6 col-xs-offset-3" style="padding: 30px;">
            <p>Name: <strong> @member.Name</strong></p>
            <img style="width:400px; height: auto; margin: 0 auto;" class="img-responsive" src="@srcPath" />
            <p>Username: @member.Username</p>
            <p><i>Email: @member.Email</i></p>
        </div>
        }

    </div>

    <div class="col-xs-6">
        <h1 class="text-center">Prospect members</h1>

        @foreach (var member in prospectMembers)
        {
            <div style="padding: 30px;">
                <p>Name: <strong> @member.Name</strong></p>
                <p><i>Email: @member.Email</i></p>
                <p>Username: @member.Username</p>
            </div>
        }
    </div>
</div>

Aarhus Web Devloper Corporation/Views/Partials/ContactForm.cshtml
@model Aarhus_Web_Devloper_Corporation.ViewModels.ContactForm
@{Layout = null;}
@if (TempData["success"] == null)
{


    using (Html.BeginUmbracoForm("HandleFormSubmit", "ContactFormSurface", new object { }, new { @class = "form-horizontal" }))
    {
    <div class="control-group">
        <div class="form-group floating-label-form-group controls">
            @Html.LabelFor(m => m.Name, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Name" })
                @Html.ValidationMessageFor(m => m.Name)
            </div>
        </div>
    </div>
    <div class="control-group">
        <div class="form-group floating-label-form-group controls">
            @Html.LabelFor(m => m.Email, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email address" })
                @Html.ValidationMessageFor(m => m.Email)
            </div>
        </div>
    </div>
    <div class="control-group">
        
        <div class="form-group floating-label-form-group controls">
            @Html.LabelFor(m => m.Subject, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Subject, new { @class = "form-control", placeholder = "Subject" })
                @Html.ValidationMessageFor(m => m.Subject)
            </div>
        </div>
    </div>
    <div class="control-group">
        <div class="form-group floating-label-form-group controls">

            @Html.LabelFor(m => m.Message, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-6">
                @Html.TextAreaFor(m => m.Message, new { @class = "form-control", placeholder = "Your message" })
                @Html.ValidationMessageFor(m => m.Message)
            </div>
        </div>
    </div>
        <div class="form-group floating-label-form-group controls">
            <div class="col-sm-offset-2 col-sm-6">
                <button id="contact-submit" type="submit" class="btn btn-primary input-medium pull-left">Send</button>
            </div>
        </div>
    }
}
else
{
    <p>Thank you for contacting us. We’ll be in touch soon!</p>
}

Aarhus Web Devloper Corporation/Views/Partials/Grid/Bootstrap2-Fluid.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container-fluid">
                <div class="row-fluid clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container-fluid'>")
        <div class="row-fluid clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style='" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "'");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

Aarhus Web Devloper Corporation/Views/Partials/Grid/Bootstrap2.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style=\"" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "\"");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

Aarhus Web Devloper Corporation/Views/Partials/Grid/Editors/Base.cshtml
@model dynamic
@using Umbraco.Web.Templates

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}

Aarhus Web Devloper Corporation/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates


<div class="video-wrapper">
	@Html.Raw(Model.value)
</div>

Aarhus Web Devloper Corporation/Views/Partials/Grid/Editors/Macro.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates


@if (Model.value != null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    ViewDataDictionary parameters = new ViewDataDictionary();
    foreach (dynamic mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @Umbraco.RenderMacro(macroAlias, parameters)
    </text>
}

Aarhus Web Devloper Corporation/Views/Partials/Grid/Editors/Rte.cshtml
@model dynamic
@using Umbraco.Web.Templates

@Html.Raw(TemplateUtilities.ParseInternalLinks(Model.value.ToString()))

Aarhus Web Devloper Corporation/Views/TextPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.TextPage>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}
  